import React from "react";
import FusionPage from "./FusionPage";
import { gameInfo } from "@/config/game.config";
import { config } from "@/config";
import { Card, CardDescription, CardHeader } from "@/components/ui/card";
import type { Metadata } from "next";
import { Separator } from "@/components/ui/separator";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"

export const metadata: Metadata = {
  title: "Pokémon Infinite Fusion Calculator | Create Custom Fusions",
  description: `The ultimate Pokémon Infinite Fusion Calculator with ${gameInfo.autoGeneratedSprites.toLocaleString()} combinations. Discover unique fusions, stats, abilities, and type matchups for your custom Pokémon creations.`,
  keywords: "infinite fusion calculator, pokemon infinite fusion calculator, pokemon fusion generator, custom pokemon creator, pokemon fusion stats",
  openGraph: {
    title: "Pokémon Infinite Fusion Calculator | Create & Share Fusions",
    description: `Generate amazing Pokémon fusions with our calculator. ${gameInfo.totalCustomSprites} custom sprites by ${gameInfo.totalArtists.toLocaleString()} artists. Perfect for trainers who want unique Pokémon combinations.`,
    url: `${config.site.mainURL}`,
    siteName: config.site.name,
    locale: "en_US",
    type: "website",
    images: [
      {
        url: "/images/og/infinite-fusion-calculator.png",
        width: 1920,
        height: 1080,
        alt: "Pokémon Infinite Fusion Calculator interface showing Charizard and Blastoise fusion examples.",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Pokémon Infinite Fusion Calculator | Create Your Dream Pokémon",
    description: `Mix any two Pokémon to create unique fusions. ${gameInfo.totalCustomSprites}+ custom sprites available. Calculate stats, abilities, and type matchups instantly.`,
    images: ["/images/og/infinite-fusion-calculator.png"],
  },
  alternates: {
    canonical: `${config.site.mainURL}`,
  },
};

const changeLogs = [
  {
    date: "2025-06-10",
    changes: [
      {
        title: "AI-Powered Fusion Suggestions",
        description:
          "Implemented a new AI recommendation system that suggests optimal fusion combinations based on your preferences and battle strategy needs. The system learns from popular community fusions and competitive meta trends.",
      },
      {
        title: "Cross-Generation Fusion Support",
        description:
          "Added compatibility for fusing Pokémon across all generations (Gen I-IX) with updated move pools and abilities. Now supports the latest Pokémon from Scarlet/Violet DLC.",
      },
    ],
  },
  {
    date: "2025-05-22",
    changes: [
      {
        title: "3D Fusion Viewer",
        description:
          "Launched our revolutionary 3D model viewer that renders fused Pokémon in full 3D with customizable animations, lighting, and camera angles. Works with all modern browsers and mobile devices.",
      },
      {
        title: "Real-Time Community Feed",
        description:
          "Added a live feed showing the most popular fusions being created worldwide right now, with upvotes and the ability to instantly try any featured fusion.",
      },
    ],
  },
  {
    date: "2025-04-15",
    changes: [
      {
        title: "Advanced Competitive Analysis",
        description:
          "New competitive tools including tier rankings for fused Pokémon, suggested EV spreads, and recommended move sets based on actual player battle data from ranked fusion battles.",
      },
    ],
  },
  {
    date: "2025-03-08",
    changes: [
      {
        title: "Fusion Breeding Simulator",
        description:
          "Added a breeding calculator that predicts egg moves, abilities, and inheritance patterns for fused Pokémon offspring, including shiny probability calculations.",
      },
      {
        title: "Augmented Reality Mode",
        description:
          "Mobile users can now view their fused Pokémon in AR space through their device camera, with options to take photos and share AR snapshots.",
      },
    ],
  },
  {
    date: "2025-02-18",
    changes: [
      {
        title: "Custom Sprite Workshop",
        description:
          "Launched an in-browser sprite editor that lets users create and submit their own fusion sprites directly through our platform, with automatic formatting for game compatibility.",
      },
    ],
  },
];

function Page() {
  return (
    <Card className="space-y-4 grid-lines bg-slate-50 dark:bg-slate-900 p-1 md:p-4">
      <CardHeader className="p-1 px-2 text-center">
        <h1 className="text-2xl">Pokémon Infinite Fusion Calculator</h1>
        <CardDescription className="mx-auto max-w-screen-xl text-muted-foreground text-sm">
          The most advanced Pokémon fusion generator online. Combine any two of {gameInfo.totalPokemons} base Pokémon to create {gameInfo.totalFusions.toLocaleString()} possible fusion combinations with custom sprites, stats, and abilities.
        </CardDescription>
      </CardHeader>

      {/* Main Fusion Calculation Section */}
      <FusionPage />

      <article>
        <Card className="mx-auto max-w-screen-md">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead colSpan={2}>
                  <h2 className="mx-auto font-bold text-xl text-center">Pokémon Fusion Statistics (v9.5)</h2>
                </TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>Base Pokémon Available</TableCell>
                <TableCell className="text-right">{gameInfo.totalPokemons}</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Total Possible Fusions</TableCell>
                <TableCell className="text-right">{gameInfo.totalFusions.toLocaleString()}</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Fusions with Custom Artwork</TableCell>
                <TableCell className="text-right">{gameInfo.totalCustomSprites.toLocaleString()}</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Total Custom Sprites</TableCell>
                <TableCell className="text-right">{gameInfo.totalCustomSprites.toLocaleString()}</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Auto-Generated Fusions</TableCell>
                <TableCell className="text-right">{gameInfo.autoGeneratedSprites.toLocaleString()}</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Custom Pokédex Entries</TableCell>
                <TableCell className="text-right">{gameInfo.totalCustomDex.toLocaleString()}</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Contributing Artists</TableCell>
                <TableCell className="text-right">{gameInfo.totalArtists.toLocaleString()}</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </Card>
        
        <Separator className="my-6" />

        <div className="space-y-4 dark:prose-invert px-2 md:px-8 pt-8 min-w-full prose">
          <h2 className="text-xl font-bold text-center">How to Use the Pokémon Infinite Fusion Calculator</h2>
          <p>
            Our <strong>Pokémon Infinite Fusion Calculator</strong> lets you combine any two Pokémon to create unique hybrid creatures. 
            Simply select a "Head" Pokémon and a "Body" Pokémon to instantly generate their fusion. The calculator provides 
            detailed information including custom sprites, base stats, abilities, and type effectiveness.
          </p>

          <h3 className="text-lg font-semibold text-center">Key Features of Our Fusion Generator</h3>
          <p>
            <strong>Custom Sprite Display:</strong> Each fusion shows either community-created artwork (credited to the artist) 
            or an auto-generated sprite. The calculator prioritizes showing custom sprites when available for the best visual experience.
          </p>

          <p>
            <strong>Comprehensive Stat Analysis:</strong> View complete stat breakdowns for your fusion including HP, Attack, 
            Defense, Special Attack, Special Defense, and Speed. Both standard and hidden abilities are displayed with detailed descriptions.
          </p>

          <p>
            <strong>Type Matchup Calculator:</strong> See how your fusion performs against all Pokémon types with our dual-type 
            effectiveness calculator. Displays 4x strengths/weaknesses and immunities for optimal battle strategy planning.
          </p>

          <h3 className="text-lg font-semibold text-center">Advanced Fusion Tools</h3>
          <p>
            <strong>Shiny Variant Preview:</strong> Toggle between different shiny versions of your fusion including head-shiny, 
            body-shiny, and full-shiny combinations to find your perfect color scheme.
          </p>

          <p>
            <strong>Sprite Gallery:</strong> Access all available sprite variations for any fusion through our sprite drawer. 
            Compare custom artwork with auto-generated options to select your preferred visual style.
          </p>

          <p>
            <strong>Pokédex Entries:</strong> Many fusions include custom Pokédex entries with unique lore. Look for the blue 
            book icon to discover these creative descriptions that bring your fusion to life.
          </p>
        </div>
      </article>

      <Separator />
      
      {/* Changelogs */}
      <section className="mt-8">
        <h2 className="mb-4 font-bold text-xl text-center">Recent Updates & Improvements</h2>
        <div className="space-y-8">
          {changeLogs.map((log, index) => (
            <div
              key={index}
              className="bg-white dark:bg-slate-800 shadow p-6 rounded-lg"
            >
              <h3 className="mb-4 font-semibold">{log.date}</h3>
              <div className="space-y-4">
                {log.changes.map((change, changeIndex) => (
                  <div key={changeIndex}>
                    <h4 className="mb-2 font-medium text-indigo-600 dark:text-indigo-400 text-lg">
                      {change.title}
                    </h4>
                    <p className="text-gray-700 dark:text-gray-300">
                      {change.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </section>
    </Card>
  );
}

export default Page;
