const gameInfo = {
  totalPokemons: 501, // Total number of base Pokémon (if different from fusions)
  totalSprites: 251001, // Total number of Pokémon fusions
  spritesWithCustomSprites: 130816, // Pokémon fusions with custom sprites
  totalCustomSprites: 180662, // Total number of custom sprites
  totalArtists: 7060, // Total number of contributing artists
  autoGeneratedSprites: 251001, // Approximate number of auto-generated sprites
  totalFusions: 251001,
  totalCustomDex: 16446,
  version: "6.4",
};

// Max stats for comparison
const maxStats = {
  MaxHP: 255,
  MaxAttack: 190,
  MaxDefense: 230,
  MaxSpAtk: 194,
  MaxSpDef: 230,
  MaxSpeed: 180,
  MaxTotal: 720,
};

const genderRatios = {
  AlwaysFemale: "100% Female",
  AlwaysMale: "100% Male",
  Female25Percent: "25% F, 75% M",
  Female50Percent: "50% F, 50% M",
  Female75Percent: "75% F, 25% M",
  FemaleOneEighth: "12.5% F, 87.5% M",
  Genderless: "Genderless",
};

const shapeDescriptions = {
  Bipedal: "Bipedal (two-legged)",
  BipedalTail: "Bipedal with a tail",
  Finned: "Finned",
  Head: "Head",
  HeadArms: "Head with arms",
  HeadBase: "Head with a base",
  HeadLegs: "Head with legs",
  Insectoid: "Insectoid",
  MultiBody: "Multiple bodies",
  MultiWinged: "Multiple wings",
  Multiped: "Multiple legs",
  Quadruped: "Quadruped (four-legged)",
  Serpentine: "Serpentine",
  Winged: "Winged",
};

export { maxStats, genderRatios, shapeDescriptions, gameInfo };
